name: Deploy AKS Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-aks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug - List Files
      run: ls -la

    - name: Change to Terraform Directory
      run: cd infrastructure  # Adjust if necessary

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name: Terraform Apply
      run: terraform apply -var-file="terraform.tfvars" -auto-approve
